databaseChangeLog:
  - changeSet:
      id: 1
      author: vladimir.dabic
      changes:
        - createTable:
            tableName: app_user
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: email
                  type: varchar(100)
                  constraints:
                    nullable: false
  - changeSet:
      id: 2
      author: vladimir.dabic
      changes:
        - createTable:
            tableName: chat
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: uuid
                  type: UUID
                  constraints:
                    primaryKey: false
                    nullable: false
              - column:
                  name: name
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: serial
                  constraints:
                    nullable: false
                    referencedTableName: app_user
                    referencedColumnNames: id
                    foreignKeyName: chat_app_user_id
  - changeSet:
      id: 3
      author: vladimir.dabic
      changes:
        - createTable:
            tableName: chat_message
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: uuid
                  type: UUID
                  constraints:
                    primaryKey: false
                    nullable: false
              - column:
                  name: content
                  type: TEXT
                  constraints:
                    nullable: false
              - column:
                  name: role
                  type: varchar(10)
                  constraints:
                    nullable: false
              - column:
                  name: chat_id
                  type: serial
                  constraints:
                    nullable: false
                    referencedTableName: chat
                    referencedColumnNames: id
                    foreignKeyName: chat_message_chat_id
              - column:
                  name: created_at
                  type: TIMESTAMPTZ
                  constraints:
                    nullable: false
